[workspace]
changelog_update = true
git_tag_enable = true
git_release_enable = true

# Changelog customization
changelog_path = "CHANGELOG.md"
changelog_include = ["feat", "fix", "perf", "refactor"]

# Automatic publication to crates.io
publish = false